### ISSUE TITLE
set up testing and continuous integration

### ISSUE THREAD

**Issue by sebkopf** [isoverse/clumpedr#1]
- [x] setup travis (linux / mac os auto tests)
- [x] setup appveyor (windows auto tests)
- [x] CI badges in README
- [x] write additional tests

**Comment by japhir** [comment]
I've added some more tests, but I notice this keeps drifting to the bottom of my todo list, even though it would surely save some pain in the future.

**Comment by japhir** [comment]
I've changed a lot of the tests to be way simpler, and to only test that particular part of the code. They are still not covering the full codebase, mostly checking if the desired output columns are available and if the output type is correct, but it's much better already!

I've just pushed some new CI code as well, that just uses the rlang default package building and docs building github actions. I had to set the package to rely on the dev version of isoreader to get these running. 0c673f45d6d8aa69a40f22313780afc75faeb2a1

**Comment by japhir** [comment]
@sebkopf How do I get rid of the continuous-integration/appveyor/branch build? I have removed the .appveyor and similarly named files and I don't see any files under the .github/workflows that relate to this.

**Comment by sebkopf** [comment]
@japhir not sure I quite follow - you can just ignore previous builds for appveyor and as long as you don't have them triggered on github anymore (via .appveyor), they'll just become obsolete. Is there something still linked to appveyor that shouldn't be that I'm missing?

**Comment by japhir** [comment]
For commit 1bac2000a292a1002f03c496f26e9115ddad60f9, where I had already removed all the .appveyor files, I still got this failed appveyor build
![2024-05-20-09:33:22_region](https://github.com/isoverse/clumpedr/assets/10659193/608e6ba4-b447-44cd-b422-60b7d8e6de4f)

I've just found in the repo settings some mentions of their API, which I've removed. So this is fixed in the commit after!
