### ISSUE TITLE
why not use R CMD check?

### ISSUE THREAD

**Issue by MartinSchobben** [isoverse/clumpedr#20]
I see that you use a makefile in the top-level directory with targets for vignette building and unit testing. Why do you not use `R CMD check` (for cran: `R CMD check --as-cran`). https://cran.r-project.org/doc/manuals/r-release/R-exts.html

**Comment by japhir** [comment]
I'm going to defer to @sebkopf here, because he wrote the makefile and pipeline for continuous integration :).

**Comment by sebkopf** [comment]
@japhir I use R CMD check for all newer packages (via `devtools::check()`), see example here: https://github.com/isoverse/isoreader/blob/master/Makefile

**Comment by sebkopf** [comment]
also, no longer use continuous integration via Travis but via GitHub actions/workflows, either should work though (but the makefile doesn't have anything to do with that, it's really just a helper for local code development): https://github.com/isoverse/isoreader/tree/master/.github

**Comment by MartinSchobben** [comment]
I suggested the same for CI to @japhir when talking to him today. The GitHub Workflows make many of these tasks (testing, building and deploying) very convenient.  I guess the makefile is then meant to create vignettes, run roxygen and perform checks in one go. I was confused as `devtools::check()` (or R CMD check) will usually do all these things (build, document and test). I presume, however, that the makefile is not meant to just produce the diagnostics, but also actually generate the documentation and vignettes. I guess this can be closed then.
