### ISSUE TITLE
cannot install package, problem with function `default()`

### ISSUE THREAD

**Issue by japhir** [isoverse/clumpedr#21]
Error in default(quiet) : could not find function "default"
Error: unable to load R code in package ‘clumpedr’

**Comment by japhir** [comment]
whoops, this is because I'm relying on `isoverse:::default()`, which I shouldn't because it's an internal function.
Will need to rewrite package options! 
@sebkopf did you change anything important about this function recently?

**Comment by andyschauer** [comment]
Same error for me.

Error in default(quiet) : could not find function "default"
Error: unable to load R code in package ‘clumpedr’

**Comment by japhir** [comment]
The problem is that the default() function was used as a default parameter argument, while I did not export the function. This means that the user has no access to this function and cannot set a default parameter value.

I have fixed this locally but it's getting late and I think I just messed up my git history. Will fix soon!

**Comment by japhir** [comment]
I just removed the `default(quiet)` from all parameters and set the quiet argument to NULL.
Within the function (where the `default` function should be available) I check whether quiet is NULL, and if so, use the `default(quiet)`. If it's not NULL, the user has set it to TRUE or FALSE (hopefully).
