### ISSUE TITLE
get subscript and superscript to work in both html and pdf documentation

### ISSUE THREAD

**Issue by japhir** [isoverse/clumpedr#3]
Seems like the current notation that I came up with after playing around with markdown's built-in `δ^13^C` and `Δ~47~`, using `\eqn{\delta^{13}}C` only works in pdf output :(.

**Comment by japhir** [comment]
For clarification, I think also `δ^13^C` didn't work.

**Comment by sebkopf** [comment]
latex (`\eqn{}`) is not rendered correctly in the R inline help because it doesn't run mathjax. That's okay and not much we can do about it. Either keep it simple with δ13C or include the `\eqn{}` and the latter will be rendered nicely in the online help and PDFs, just look a bit wacky in the inline help. The `^sup^` and `~sub~` syntax is sadly not supported.

**Comment by japhir** [comment]
I found out that the `\eqn{}` takes a second argument, which defines how it should display plaintext. The source files become a bit more cumbersome, but now the docs can show `δ13C` in plain text and html, and `$\delta^{13}$C` in LaTeX.

See https://cran.r-project.org/doc/manuals/R-exts.html#Mathematics

i.e. the header of `bulk_and_clumping_deltas.R` now becomes:
```{r}
#' Compute \eqn{\delta^{13}}{δ13}C, \eqn{\delta^{18}}{δ18}O \eqn{\Delta_{47}}{Δ47},
#' \eqn{\Delta_{48}}{Δ48}, and \eqn{\Delta_{49}}{Δ49} values
```

**Comment by japhir** [comment]
Still doesn't work for function titles.

**Comment by japhir** [comment]
Looks like this [SO answer](https://stackoverflow.com/a/47539862/5252333) may solve this issue. Damn, that'll be cumbersome though...
```
\ifelse{html}{\out{HTML CODE}}{\eqn{LATEX-LIKE CODE}{ASCII}}
```

**Comment by japhir** [comment]
[SO](https://stackoverflow.com/a/3782694/5252333) also suggests to bracket with `[` and `]` for subscript, and prefix with `^` for superscript. But I think `δ^13C` is uglier than `δ13C`, and everyone knows what it's supposed to look like ;-).

**Comment by japhir** [comment]
I'll just not use them in titles.
