### ISSUE TITLE
Show several parameters in info message

### ISSUE THREAD

**Issue by japhir** [isoverse/clumpedr#8]
Sometimes I'd like to show the values of a vector in an info message, like here: 
https://github.com/isoverse/clumpedr/blob/87810f10cd65fc0d4a7afa2569f550da4bb54ac7/R/spread_intensities.R#L30

However, pasting it together with the rest of the message repeats the character part every time. @sebkopf any idea how to get something like this:
```{r}
library(dplyr)
library(glue)
vars <- c(1, 5, 3, 9)
glue("Info: parameter values are: {vars}") %>%
 message()
```
to print:
`"Info:parameter values are: 1, 5, 3, 9"` in stead of repeating the character part?

**Comment by japhir** [comment]
probably something with [`glue::glue_collapse()`](https://glue.tidyverse.org/reference/glue_collapse.html)

**Comment by sebkopf** [comment]
`glue_collapse` works for that, but you can also use a simply base R `paste(..., collapse = ", ")` e.g.:

`glue("Info: parameter values are: {paste(vars, collapse = ', ')}") %>% message()`

glue_collapse used to be called just collapse but was recently renamed so make sure to require a recent version of the glue package in your description if you do use it
