### ISSUE TITLE
Continue ETF calculation per Preparation, even when one of the `lm` calls fails

### ISSUE THREAD

**Issue by japhir** [isoverse/clumpedr#9]
https://github.com/isoverse/clumpedr/blob/f62cb23bdf277afab0d1700b812afed4b11a484a/R/empirical_transfer_function.R#L74

I use `dplyr::do` to calculate a `lm` within groups, but sometimes a group has too few values, or some `NA` values, or something else happens that makes the lm call fail with en error. It would be better if the function would continue calculations with a warning and return _NA_real in stead.
I've had a look at [purrr::safely](https://www.rdocumentation.org/packages/purrr/versions/0.2.2.2/topics/safely) for this, but couldn't get it to work. Any ideas @sebkopf? :)

**Comment by japhir** [comment]
Should be solved with https://github.com/isoverse/clumpedr/commit/9757fa40cee5b45a44bcf5d752d4d532c8e3d8fc

**Comment by sebkopf** [comment]
hi @japhir 
totally missed this one but if you figured it out, all good :) `safely` is definitely a useful way to go, just for info, here is a recent example I used with non linear regressions (which always have a risk of failing)
```
# using safely to catch problems with the non-linear fit
safe_nls <- safely(nls)

# calibration fit
calib_fits <- calibs %>% 
  mutate(
    lm_fit = map(
      data, 
      ~lm(Std_Area ~ Std_Amount, data = .x)
    ),
    lm_summary = map(lm_fit, glance),
    lm_coefs = map(lm_fit, tidy),
    a = map_dbl(lm_coefs, ~filter(.x, term == "(Intercept)")$estimate),
    b = a / map_dbl(lm_coefs, ~filter(.x, term == "Std_Amount")$estimate),
    nls_safe_fit = pmap(
      list(data = data, a = a, b = b),
      function(data, a, b) {
        safe_nls(Std_Area ~ a * exp(b * Std_Amount), data = data, start = list(a = a, b = b))
      }
    ),
    nls_fit_error = map_chr(
      nls_safe_fit, 
      ~if(is.null(.x$error)) {NA_character_} else {.x$error$message}),
    nls_fit = map(nls_safe_fit, "result"),
    nls_summary = map(nls_fit, ~if(!is.null(.x)) { glance(.x) } else { NULL }),
    nls_coefs = map(nls_fit, ~if(!is.null(.x)) { tidy(.x) } else { NULL })
  ) %>% select(-nls_safe_fit, -a, -b) 

```
